### ISSUE TITLE
挂着代理时程序无法正常使用

### ISSUE THREAD

**Issue by chingkingm** [yllhwa/GenshinSpider#1]
我开着[Clash](https://github.com/Fndroid/clash_for_windows_pkg)，

首先get_token程序无法获取token，会在极短的时间内输出错误信息，然后自行关闭窗口。
<details>
  <summary>错误信息（截图。。）</summary>
   
![Snipaste_2021-02-20_15-22-01.png](https://i.loli.net/2021/02/20/yKhmv5fn2tu7PAI.png)
![Snipaste_2021-02-20_15-20-22.png](https://i.loli.net/2021/02/20/TtEIsnC5XdB8M9Q.png)
</details>

然后，token正确添加的情况下，主程序会报 *识别圣遗物出错*。

**Comment by yllhwa** [comment]
已确认是request库的问题使得在代理情况下ssl认证失败，下个版本将会修复。

**Comment by yllhwa** [comment]
修复完毕
