### ISSUE TITLE
在分辨率为2560*1080的21:9显示比例中，抓取的圣遗物信息不对。

### ISSUE THREAD

**Issue by YouKnowMyEggs** [yllhwa/GenshinSpider#2]
![QQ截图20210221162905](https://user-images.githubusercontent.com/18475010/108619785-05ed8000-7462-11eb-9681-91690885ed6f.png)

**Comment by yllhwa** [comment]
请参见README中关于配置文件[grasp_setting]的说明，可能需要手动适配一下比例。

**Comment by YouKnowMyEggs** [comment]
> 请参见README中关于配置文件[grasp_setting]的说明，可能需要手动适配一下比例。

谢谢，参数left改为0.70就好了。
