### ISSUE TITLE
平雷套装保存时出错

### ISSUE THREAD

**Issue by Lycreal** [yllhwa/GenshinSpider#3]
https://github.com/yllhwa/GenshinSpider/blob/5664b3aa3e9a374bb295662fa8511dc1386dd9fc/GenshinSpider/mainwindow.py#L27

应为`平息鸣雷的尊者`

**Comment by yllhwa** [comment]
感谢反馈和定位错误，将在下个版本修复。

**Comment by yllhwa** [comment]
修复完毕，将于下个版本将文字内容分离，并重构整理剪切板部分的代码。
再次感谢。
