### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by ZrO2Bit** [yllhwa/GenshinSpider#4]
QApplication.primaryScreen().grabWindow(handle)可以直接根据句柄获得截图
config可以直接保存为python格式，import python文件就直接读取了（反正你config也不用再程序里更改

**Comment by yllhwa** [comment]
thx, self.qt.api++.
config是允许用户修改的，保存为python格式不方便打包为二进制后修改😄
另：本项目已停止维护，圣遗物识别相关内容可移步https://github.com/ChanIok/JumpyDumpty

代码质量相关内容可以帮助我code review,这是我第一次写pyqt.😂
